= Microsoft Azure의 HPC

Microsoft Azure는 HPC를 위한 포괄적인 클라우드 기반 인프라를 제공하여 복잡한 시뮬레이션, AI 모델링, 데이터 분석 등 다양한 연산 집약적인 작업을 지원합니다. Azure의 HPC 솔루션은 확장성, 보안, 비용 효율성을 갖춘 엔터프라이즈 급 인프라를 통해 기업과 연구기관의 요구를 충족합니다.

Microsoft Azure는 클라우드 기반 HPC 솔루션을 제공하여 대규모 연산, 데이터 분석, AI 모델 학습 등 계산 집약적인 작업을 효율적으로 수행할 수 있도록 지원합니다. Azure HPC는 전통적 온프레미스 HPC와 유사한 기술적 구성 요소를 가지면서, 클라우드 환경의 탄력성, 확장성, 서비스화 기능을 통합한 구성을 갖습니다. HPC 시스템을 빌드하는데는 많은 인프라 구성 요소가 필요합니다.  HPC 워크로드를 관리하는 방법으로 무엇을 선택하든 컴퓨팅, 스토리지 및 네트워킹은 기본 구성 요소를 제공합니다.

== 컴퓨팅 리소스

Azure는 CPU및 GPU 사용량이 많은 워크로드에 최적화된 크기 범위를 제공합니다.

=== 가상 머신

==== CPU 기반 가상 머신

Azure 고성능 컴퓨팅 VM은 계산 유체 역학, 유한 요소 분석, 프런트 엔드 및 백 엔드 EDA, 렌더링, 분자 역학, 계산 지질 과학, 날씨 시뮬레이션 및 재무 위험 분석과 같은 다양한 HPC 워크로드에 최적화되어 있습니다.

[cols="1,2a,2a", options="header"]
|===
|패밀리|워크로드|계열 목록
|HB 제품군|높은 메모리 대역폭 + 
유체 역학 + 
날씨 모델링	
|HBv2 시리즈 + 
HBv3 시리즈 + 
HBv4 시리즈
|HC 제품군|고밀도 컴퓨팅 +
 유한 요소 분석 +
 분자 역학 +
 계산 화학
|HC 시리즈
|HX 패밀리|대용량 메모리 용량 +
 EDA(전자 디자인 자동화)|HX 시리즈
|===

==== GPU 사용 가상 머신

N 시리즈 VM은 AI(인공지능) 학습 및 시각화를 포함한 계산 집약적 또는 그래픽 집약적 애플리케이션을 위해 설계된 NVIDIA GPU를 특징으로 합니다.

[cols="1,2a,2a", options="header"]
|===
|패밀리|워크로드|계열 목록
|NC 패밀리|
|===

=== 스토리지

대규모 Batch 및 HPC 작업에는 기존 클라우드 파일 시스템의 용량을 초과하는 데이터 스토리지 및 액세스에 대한 요구사항이 있습니다. Azure 기반 HPC 애플리케이션의 속도 및 용량 요구사항을 관리하는 솔루션은 다양합니다.

==== Azure HPC 캐시



=== 네트워크

H16r, H16mr, A8 및 A9 VM은 높은 처리량 백 엔드 RDMA 네트워크에 연결할 수 있습니다. 이 네트워크는 MPI 또는 Intel MPI로 더 잘 알려진 Microsoft 메시지 전달 인터페이스에서 실행되는 긴밀하게 결합된 병렬 애플리케이션의 성능을 향상시킬 수 있습니다.

* RDMA 지원 인스턴스
* 가상 네트워크
* Express Route

=== 관리

==== Azure Batch

Azure Batch는 클라우드에서 대규모 병렬 및 HPC 애플리케이션을 효율적으로 실행하기 위핸 플랫폼 서비스입니다. Azure Batch는 가상 머신의 관리되는 풀에서 실행되는 컴퓨팅 집약적 작업을 예약하고, 작업 요구에 맞게 컴퓨링 리소스를 자동으로 크기 조정할 수 있습니다.

SaaS 공급자 및 개발자는 Batch SDK 및 도구를 사용하여 HPC 애플리케이션 또는 컨테이너 작업을 Azure에 통합하고, 데이터를 Azure로 스테이징하고, 작업 실행 파이프라인을 빌드할 수 있습니다.

Azure Batch에서 모든 서비스가 클라우드에서 실행되고 있는 경우 아래 이미지는 Azure Batch를 사용하여 아키텍처가 어떻게 보이는지 보여주며, 클라우드에서 실행중인 확장성 및 작업 일정 구성과 결과 및 보고서를 온-프레미스 환경으로 보낼 수 있습니다.

=== CycleCloud

